# Vague for Alacritty
# -------------------
# Theme Author: vague2k <ilovedrawing056@gmail.com>
# Ported by:	skewb1k <skewb1kunix@gmail.com>
# License:  	MIT License
# Upstream: 	https://github.com/vague2k/vague.nvim/blob/main/extras/alacritty/vague.toml

[colors.primary]
background = '#141415'
foreground = '#cdcdcd'

[colors.normal]
black = '#252530'
red = '#d8647e'
green = '#7fa563'
yellow = '#f3be7c'
blue = '#6e94b2'
magenta = '#bb9dbd'
cyan = '#aeaed1'
white = '#cdcdcd'

[colors.bright]
black = '#606079'
red = '#d8647e'
green = '#7fa563'
yellow = '#f3be7c'
blue = '#6e94b2'
magenta = '#bb9dbd'
cyan = '#aeaed1'
white = '#d7d7d7'
